"""initial schema

Revision ID: 7ce5c0e3316b
Revises: 
Create Date: 2026-06-18 16:13:55.316052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '7ce5c0e3316b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashflow_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cashflow_type', sa.String(length=30), nullable=False),
    sa.Column('match_text', sa.String(length=255), nullable=False),
    sa.Column('match_field', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashflow_rules_cashflow_type'), 'cashflow_rules', ['cashflow_type'], unique=False)
    op.create_index(op.f('ix_cashflow_rules_direction'), 'cashflow_rules', ['direction'], unique=False)
    op.create_index(op.f('ix_cashflow_rules_id'), 'cashflow_rules', ['id'], unique=False)
    op.create_index(op.f('ix_cashflow_rules_is_active'), 'cashflow_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_cashflow_rules_match_text'), 'cashflow_rules', ['match_text'], unique=False)
    op.create_index(op.f('ix_cashflow_rules_source'), 'cashflow_rules', ['source'], unique=False)
    op.create_index(op.f('ix_cashflow_rules_user_id'), 'cashflow_rules', ['user_id'], unique=False)
    op.create_table('category_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('match_text', sa.String(length=255), nullable=False),
    sa.Column('match_field', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_rules_category'), 'category_rules', ['category'], unique=False)
    op.create_index(op.f('ix_category_rules_direction'), 'category_rules', ['direction'], unique=False)
    op.create_index(op.f('ix_category_rules_id'), 'category_rules', ['id'], unique=False)
    op.create_index(op.f('ix_category_rules_is_active'), 'category_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_category_rules_match_text'), 'category_rules', ['match_text'], unique=False)
    op.create_index(op.f('ix_category_rules_source'), 'category_rules', ['source'], unique=False)
    op.create_index(op.f('ix_category_rules_user_id'), 'category_rules', ['user_id'], unique=False)
    op.create_table('description_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cleaned_description', sa.String(length=255), nullable=False),
    sa.Column('match_text', sa.String(length=255), nullable=False),
    sa.Column('match_field', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_description_rules_cleaned_description'), 'description_rules', ['cleaned_description'], unique=False)
    op.create_index(op.f('ix_description_rules_direction'), 'description_rules', ['direction'], unique=False)
    op.create_index(op.f('ix_description_rules_id'), 'description_rules', ['id'], unique=False)
    op.create_index(op.f('ix_description_rules_is_active'), 'description_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_description_rules_match_text'), 'description_rules', ['match_text'], unique=False)
    op.create_index(op.f('ix_description_rules_source'), 'description_rules', ['source'], unique=False)
    op.create_index(op.f('ix_description_rules_user_id'), 'description_rules', ['user_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_id'), 'import_batches', ['id'], unique=False)
    op.create_index(op.f('ix_import_batches_source'), 'import_batches', ['source'], unique=False)
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_index(op.f('ix_import_batches_user_id'), 'import_batches', ['user_id'], unique=False)
    op.create_table('investment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('instrument_name', sa.String(length=255), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('isin', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('original_currency', sa.String(length=3), nullable=True),
    sa.Column('fx_rate_to_eur', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fx_rate_source', sa.String(length=30), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('funding_source', sa.String(length=50), nullable=True),
    sa.Column('funding_match_status', sa.String(length=30), nullable=True),
    sa.Column('matched_transaction_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_events_date'), 'investment_events', ['date'], unique=False)
    op.create_index(op.f('ix_investment_events_event_type'), 'investment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_investment_events_funding_match_status'), 'investment_events', ['funding_match_status'], unique=False)
    op.create_index(op.f('ix_investment_events_funding_source'), 'investment_events', ['funding_source'], unique=False)
    op.create_index(op.f('ix_investment_events_id'), 'investment_events', ['id'], unique=False)
    op.create_index(op.f('ix_investment_events_import_batch_id'), 'investment_events', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_investment_events_isin'), 'investment_events', ['isin'], unique=False)
    op.create_index(op.f('ix_investment_events_matched_transaction_id'), 'investment_events', ['matched_transaction_id'], unique=False)
    op.create_index(op.f('ix_investment_events_source'), 'investment_events', ['source'], unique=False)
    op.create_index(op.f('ix_investment_events_ticker'), 'investment_events', ['ticker'], unique=False)
    op.create_index(op.f('ix_investment_events_transaction_id'), 'investment_events', ['transaction_id'], unique=False)
    op.create_index('ix_investment_events_user_dedupe_hash', 'investment_events', ['user_id', 'dedupe_hash'], unique=True)
    op.create_index(op.f('ix_investment_events_user_id'), 'investment_events', ['user_id'], unique=False)
    op.create_table('market_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('isin', sa.String(length=50), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'isin', 'price_date', 'source', name='uq_market_price_history_identity')
    )
    op.create_index(op.f('ix_market_price_history_currency'), 'market_price_history', ['currency'], unique=False)
    op.create_index(op.f('ix_market_price_history_fetched_at'), 'market_price_history', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_market_price_history_id'), 'market_price_history', ['id'], unique=False)
    op.create_index(op.f('ix_market_price_history_isin'), 'market_price_history', ['isin'], unique=False)
    op.create_index(op.f('ix_market_price_history_price_date'), 'market_price_history', ['price_date'], unique=False)
    op.create_index(op.f('ix_market_price_history_source'), 'market_price_history', ['source'], unique=False)
    op.create_index(op.f('ix_market_price_history_ticker'), 'market_price_history', ['ticker'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('isin', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_prices_currency'), 'market_prices', ['currency'], unique=False)
    op.create_index(op.f('ix_market_prices_fetched_at'), 'market_prices', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_market_prices_id'), 'market_prices', ['id'], unique=False)
    op.create_index(op.f('ix_market_prices_isin'), 'market_prices', ['isin'], unique=False)
    op.create_index(op.f('ix_market_prices_source'), 'market_prices', ['source'], unique=False)
    op.create_index(op.f('ix_market_prices_ticker'), 'market_prices', ['ticker'], unique=False)
    op.create_table('owed_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('person', sa.String(length=100), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_remaining', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('linked_transaction_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owed_items_id'), 'owed_items', ['id'], unique=False)
    op.create_index(op.f('ix_owed_items_import_batch_id'), 'owed_items', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_owed_items_linked_transaction_id'), 'owed_items', ['linked_transaction_id'], unique=False)
    op.create_index(op.f('ix_owed_items_person'), 'owed_items', ['person'], unique=False)
    op.create_index(op.f('ix_owed_items_source'), 'owed_items', ['source'], unique=False)
    op.create_index(op.f('ix_owed_items_status'), 'owed_items', ['status'], unique=False)
    op.create_index('ix_owed_items_user_dedupe_hash', 'owed_items', ['user_id', 'dedupe_hash'], unique=True)
    op.create_index(op.f('ix_owed_items_user_id'), 'owed_items', ['user_id'], unique=False)
    op.create_table('owed_payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('owed_payment_id', sa.Integer(), nullable=False),
    sa.Column('owed_item_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owed_payment_allocations_id'), 'owed_payment_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_owed_payment_allocations_owed_item_id'), 'owed_payment_allocations', ['owed_item_id'], unique=False)
    op.create_index(op.f('ix_owed_payment_allocations_owed_payment_id'), 'owed_payment_allocations', ['owed_payment_id'], unique=False)
    op.create_index(op.f('ix_owed_payment_allocations_user_id'), 'owed_payment_allocations', ['user_id'], unique=False)
    op.create_table('owed_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('person', sa.String(length=100), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owed_payments_id'), 'owed_payments', ['id'], unique=False)
    op.create_index(op.f('ix_owed_payments_linked_transaction_id'), 'owed_payments', ['linked_transaction_id'], unique=False)
    op.create_index(op.f('ix_owed_payments_method'), 'owed_payments', ['method'], unique=False)
    op.create_index(op.f('ix_owed_payments_payment_date'), 'owed_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_owed_payments_person'), 'owed_payments', ['person'], unique=False)
    op.create_index(op.f('ix_owed_payments_user_id'), 'owed_payments', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('original_currency', sa.String(length=3), nullable=True),
    sa.Column('fx_rate_to_eur', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fx_rate_source', sa.String(length=30), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('cashflow_type', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('merchant', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_cashflow_type'), 'transactions', ['cashflow_type'], unique=False)
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_direction'), 'transactions', ['direction'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_import_batch_id'), 'transactions', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_source'), 'transactions', ['source'], unique=False)
    op.create_index('ix_transactions_user_dedupe_hash', 'transactions', ['user_id', 'dedupe_hash'], unique=True)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('wealth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('institution', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wealth_accounts_account_type'), 'wealth_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_wealth_accounts_currency'), 'wealth_accounts', ['currency'], unique=False)
    op.create_index(op.f('ix_wealth_accounts_id'), 'wealth_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_wealth_accounts_is_active'), 'wealth_accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_wealth_accounts_name'), 'wealth_accounts', ['name'], unique=False)
    op.create_index(op.f('ix_wealth_accounts_user_id'), 'wealth_accounts', ['user_id'], unique=False)
    op.create_table('wealth_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance_eur', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fx_rate_to_eur', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('interest_earned', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wealth_snapshots_account_id'), 'wealth_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_wealth_snapshots_currency'), 'wealth_snapshots', ['currency'], unique=False)
    op.create_index(op.f('ix_wealth_snapshots_external_id'), 'wealth_snapshots', ['external_id'], unique=False)
    op.create_index(op.f('ix_wealth_snapshots_id'), 'wealth_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_wealth_snapshots_import_batch_id'), 'wealth_snapshots', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_wealth_snapshots_snapshot_date'), 'wealth_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_wealth_snapshots_source'), 'wealth_snapshots', ['source'], unique=False)
    op.create_index('ix_wealth_snapshots_user_dedupe_hash', 'wealth_snapshots', ['user_id', 'dedupe_hash'], unique=True)
    op.create_index(op.f('ix_wealth_snapshots_user_id'), 'wealth_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wealth_snapshots_user_id'), table_name='wealth_snapshots')
    op.drop_index('ix_wealth_snapshots_user_dedupe_hash', table_name='wealth_snapshots')
    op.drop_index(op.f('ix_wealth_snapshots_source'), table_name='wealth_snapshots')
    op.drop_index(op.f('ix_wealth_snapshots_snapshot_date'), table_name='wealth_snapshots')
    op.drop_index(op.f('ix_wealth_snapshots_import_batch_id'), table_name='wealth_snapshots')
    op.drop_index(op.f('ix_wealth_snapshots_id'), table_name='wealth_snapshots')
    op.drop_index(op.f('ix_wealth_snapshots_external_id'), table_name='wealth_snapshots')
    op.drop_index(op.f('ix_wealth_snapshots_currency'), table_name='wealth_snapshots')
    op.drop_index(op.f('ix_wealth_snapshots_account_id'), table_name='wealth_snapshots')
    op.drop_table('wealth_snapshots')
    op.drop_index(op.f('ix_wealth_accounts_user_id'), table_name='wealth_accounts')
    op.drop_index(op.f('ix_wealth_accounts_name'), table_name='wealth_accounts')
    op.drop_index(op.f('ix_wealth_accounts_is_active'), table_name='wealth_accounts')
    op.drop_index(op.f('ix_wealth_accounts_id'), table_name='wealth_accounts')
    op.drop_index(op.f('ix_wealth_accounts_currency'), table_name='wealth_accounts')
    op.drop_index(op.f('ix_wealth_accounts_account_type'), table_name='wealth_accounts')
    op.drop_table('wealth_accounts')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index('ix_transactions_user_dedupe_hash', table_name='transactions')
    op.drop_index(op.f('ix_transactions_source'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_import_batch_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_direction'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_cashflow_type'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_owed_payments_user_id'), table_name='owed_payments')
    op.drop_index(op.f('ix_owed_payments_person'), table_name='owed_payments')
    op.drop_index(op.f('ix_owed_payments_payment_date'), table_name='owed_payments')
    op.drop_index(op.f('ix_owed_payments_method'), table_name='owed_payments')
    op.drop_index(op.f('ix_owed_payments_linked_transaction_id'), table_name='owed_payments')
    op.drop_index(op.f('ix_owed_payments_id'), table_name='owed_payments')
    op.drop_table('owed_payments')
    op.drop_index(op.f('ix_owed_payment_allocations_user_id'), table_name='owed_payment_allocations')
    op.drop_index(op.f('ix_owed_payment_allocations_owed_payment_id'), table_name='owed_payment_allocations')
    op.drop_index(op.f('ix_owed_payment_allocations_owed_item_id'), table_name='owed_payment_allocations')
    op.drop_index(op.f('ix_owed_payment_allocations_id'), table_name='owed_payment_allocations')
    op.drop_table('owed_payment_allocations')
    op.drop_index(op.f('ix_owed_items_user_id'), table_name='owed_items')
    op.drop_index('ix_owed_items_user_dedupe_hash', table_name='owed_items')
    op.drop_index(op.f('ix_owed_items_status'), table_name='owed_items')
    op.drop_index(op.f('ix_owed_items_source'), table_name='owed_items')
    op.drop_index(op.f('ix_owed_items_person'), table_name='owed_items')
    op.drop_index(op.f('ix_owed_items_linked_transaction_id'), table_name='owed_items')
    op.drop_index(op.f('ix_owed_items_import_batch_id'), table_name='owed_items')
    op.drop_index(op.f('ix_owed_items_id'), table_name='owed_items')
    op.drop_table('owed_items')
    op.drop_index(op.f('ix_market_prices_ticker'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_source'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_isin'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_id'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_fetched_at'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_currency'), table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_market_price_history_ticker'), table_name='market_price_history')
    op.drop_index(op.f('ix_market_price_history_source'), table_name='market_price_history')
    op.drop_index(op.f('ix_market_price_history_price_date'), table_name='market_price_history')
    op.drop_index(op.f('ix_market_price_history_isin'), table_name='market_price_history')
    op.drop_index(op.f('ix_market_price_history_id'), table_name='market_price_history')
    op.drop_index(op.f('ix_market_price_history_fetched_at'), table_name='market_price_history')
    op.drop_index(op.f('ix_market_price_history_currency'), table_name='market_price_history')
    op.drop_table('market_price_history')
    op.drop_index(op.f('ix_investment_events_user_id'), table_name='investment_events')
    op.drop_index('ix_investment_events_user_dedupe_hash', table_name='investment_events')
    op.drop_index(op.f('ix_investment_events_transaction_id'), table_name='investment_events')
    op.drop_index(op.f('ix_investment_events_ticker'), table_name='investment_events')
    op.drop_index(op.f('ix_investment_events_source'), table_name='investment_events')
    op.drop_index(op.f('ix_investment_events_matched_transaction_id'), table_name='investment_events')
    op.drop_index(op.f('ix_investment_events_isin'), table_name='investment_events')
    op.drop_index(op.f('ix_investment_events_import_batch_id'), table_name='investment_events')
    op.drop_index(op.f('ix_investment_events_id'), table_name='investment_events')
    op.drop_index(op.f('ix_investment_events_funding_source'), table_name='investment_events')
    op.drop_index(op.f('ix_investment_events_funding_match_status'), table_name='investment_events')
    op.drop_index(op.f('ix_investment_events_event_type'), table_name='investment_events')
    op.drop_index(op.f('ix_investment_events_date'), table_name='investment_events')
    op.drop_table('investment_events')
    op.drop_index(op.f('ix_import_batches_user_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_source'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_description_rules_user_id'), table_name='description_rules')
    op.drop_index(op.f('ix_description_rules_source'), table_name='description_rules')
    op.drop_index(op.f('ix_description_rules_match_text'), table_name='description_rules')
    op.drop_index(op.f('ix_description_rules_is_active'), table_name='description_rules')
    op.drop_index(op.f('ix_description_rules_id'), table_name='description_rules')
    op.drop_index(op.f('ix_description_rules_direction'), table_name='description_rules')
    op.drop_index(op.f('ix_description_rules_cleaned_description'), table_name='description_rules')
    op.drop_table('description_rules')
    op.drop_index(op.f('ix_category_rules_user_id'), table_name='category_rules')
    op.drop_index(op.f('ix_category_rules_source'), table_name='category_rules')
    op.drop_index(op.f('ix_category_rules_match_text'), table_name='category_rules')
    op.drop_index(op.f('ix_category_rules_is_active'), table_name='category_rules')
    op.drop_index(op.f('ix_category_rules_id'), table_name='category_rules')
    op.drop_index(op.f('ix_category_rules_direction'), table_name='category_rules')
    op.drop_index(op.f('ix_category_rules_category'), table_name='category_rules')
    op.drop_table('category_rules')
    op.drop_index(op.f('ix_cashflow_rules_user_id'), table_name='cashflow_rules')
    op.drop_index(op.f('ix_cashflow_rules_source'), table_name='cashflow_rules')
    op.drop_index(op.f('ix_cashflow_rules_match_text'), table_name='cashflow_rules')
    op.drop_index(op.f('ix_cashflow_rules_is_active'), table_name='cashflow_rules')
    op.drop_index(op.f('ix_cashflow_rules_id'), table_name='cashflow_rules')
    op.drop_index(op.f('ix_cashflow_rules_direction'), table_name='cashflow_rules')
    op.drop_index(op.f('ix_cashflow_rules_cashflow_type'), table_name='cashflow_rules')
    op.drop_table('cashflow_rules')
    # ### end Alembic commands ###
